### ISSUE TITLE
SP2 - Đặc tả yêu cầu

### ISSUE THREAD

**Issue by gooofff** [Gooofff-team/CNPM#10]
Nộp trước 12/12
Ghi rõ tên phần mình làm (VD: Cường - FDD, DFD)

**Comment by gooofff** [comment]
Cường - FDD,DFD)
[DFD,FDD.docx](https://github.com/Gooofff-team/CNPM/files/10199460/DFD.FDD.docx)

**Comment by hoangducdungvn** [comment]
Dũng - SD,ERD


[SD_ERD_SP2.docx](https://github.com/Gooofff-team/CNPM/files/10201542/SD_ERD_SP2.docx)

**Comment by datto2003** [comment]
Đạt - UC

[dtyc2.docx](https://github.com/Gooofff-team/CNPM/files/10202413/dtyc2.docx)
