### ISSUE TITLE
SP2 - Phân tích thiết kế

### ISSUE THREAD

**Issue by gooofff** [Gooofff-team/CNPM#11]
Nộp trước 14/12
Ghi rõ tên phần mình làm (VD: Cường - FDD, DFD)

**Comment by snowball-512** [comment]
[Thietkedl-1.docx](https://github.com/Gooofff-team/CNPM/files/10218696/Thietkedl-1.docx) (Hương - Thiết kế dữ liệu)

**Comment by giangkoi65** [comment]
Giang - Thiết kế kiến trúc
[thiet_ke_kien_truc.docx](https://github.com/Gooofff-team/CNPM/files/10219245/thiet_ke_kien_truc.docx)

**Comment by anhmanh103** [comment]
Mạnh - Thiết kế giao diện




[thietkegiaodien_sp2.docx](https://github.com/Gooofff-team/CNPM/files/10220064/thietkegiaodien_sp2.docx)
