### ISSUE TITLE
SP2 - Kiểm thử

### ISSUE THREAD

**Issue by gooofff** [Gooofff-team/CNPM#13]
Nộp trước 20/12
Ghi rõ tên phần mình làm (VD: Cường - FDD, DFD)

**Comment by gooofff** [comment]
Kiểm thử chức năng  - Cường 
https://docs.google.com/spreadsheets/d/129SX3GNCy6VOKHqOPaDD9njoQas1eoXagO47cJ86cd4/edit?usp=sharing

**Comment by giangkoi65** [comment]
Kiểm thử giao diện - Giang
https://docs.google.com/spreadsheets/d/1unz_Bdfj6o-7uFybtCenn5SI1CKQoBnc3p2hHBEoNR0/edit?usp=sharing
