### ISSUE TITLE
Đặc tả yêu cầu - UC

### ISSUE THREAD

**Issue by gooofff** [Gooofff-team/CNPM#2]

**Comment by gooofff** [comment]
Gửi bài trước 2/12

**Comment by datto2003** [comment]
[usecase.docx](https://github.com/Gooofff-team/CNPM/files/10132913/usecase.docx)

**Comment by datto2003** [comment]
Usecase sửa lại

[usecase1.docx](https://github.com/Gooofff-team/CNPM/files/10133171/usecase1.docx)
