### ISSUE TITLE
Đặc tả yêu cầu - SD, ERD

### ISSUE THREAD

**Issue by gooofff** [Gooofff-team/CNPM#3]

**Comment by gooofff** [comment]
gửi bài trước 2/12

**Comment by hoangducdungvn** [comment]
[Sequence diagram and ERD.docx](https://github.com/Gooofff-team/CNPM/files/10134220/Sequence.diagram.and.ERD.docx)

**Comment by gooofff** [comment]
Mở chỉnh sửa, nộp trước 7/10

**Comment by hoangducdungvn** [comment]
[Sequence diagram and ERD.docx](https://github.com/Gooofff-team/CNPM/files/10160581/Sequence.diagram.and.ERD.docx)

**Comment by gooofff** [comment]
chỉnh sửa ERD

**Comment by hoangducdungvn** [comment]
[Sequence diagram and ERD.docx](https://github.com/Gooofff-team/CNPM/files/10163819/Sequence.diagram.and.ERD.docx)

**Comment by hoangducdungvn** [comment]
[Sequence diagram and ERD.docx](https://github.com/Gooofff-team/CNPM/files/10168116/Sequence.diagram.and.ERD.docx)
