### ISSUE TITLE
Thiết kế phần mềm - thiết kế kiến trúc, thiết kế dữ liệu 

### ISSUE THREAD

**Issue by gooofff** [Gooofff-team/CNPM#4]
nộp trước 4/12
Giang thiết kế kiến trúc và thiết kế dữ liệu

**Comment by gooofff** [comment]
Giang hoặc Hương đại diện nộp thiết kế dữ liệu

**Comment by giangkoi65** [comment]
[thiet_ke_kien_truc.docx](https://github.com/Gooofff-team/CNPM/files/10146878/thiet_ke_kien_truc.docx)

**Comment by gooofff** [comment]
Mở chỉnh sửa, nộp trước 7/10
Thiết kế kiến trúc

**Comment by giangkoi65** [comment]
[thiet_ke_kien_truc.docx](https://github.com/Gooofff-team/CNPM/files/10164599/thiet_ke_kien_truc.docx)

**Comment by giangkoi65** [comment]
[thiet_ke_kien_truc.docx](https://github.com/Gooofff-team/CNPM/files/10164820/thiet_ke_kien_truc.docx)
