### ISSUE TITLE
Thiết kế phần mềm - Thiết kế đối tượng và thiết kế dữ liệu

### ISSUE THREAD

**Issue by gooofff** [Gooofff-team/CNPM#6]
nộp trước 4/12
Hương thiết kế đối tượng và thiết kế dữ liệu

**Comment by gooofff** [comment]
Giang hoặc Hương đại diện nộp thiết kế dữ liệu

**Comment by snowball-512** [comment]
[Thietkedulieu.docx](https://github.com/Gooofff-team/CNPM/files/10146948/Thietkedulieu.docx)

**Comment by gooofff** [comment]
Mở chỉnh sửa, nộp trước 7/10
Thiết kế dữ liệu

**Comment by snowball-512** [comment]
[Thietkedl.docx](https://github.com/Gooofff-team/CNPM/files/10167354/Thietkedl.docx)
