### ISSUE TITLE
Kiểm thử -  Giao diện, Chức năng

### ISSUE THREAD

**Issue by gooofff** [Gooofff-team/CNPM#9]
Nộp trước 10/12

**Comment by gooofff** [comment]
https://docs.google.com/spreadsheets/d/1UHgK6kiG_yfbO8RyIRffxmWSbBGhMIkGlbt5z6mRDMo/edit#gid=0

Kiểm thử giao diện

**Comment by datto2003** [comment]
https://docs.google.com/spreadsheets/d/1xvT_az9nSFsKbyJov_hgyfEJDDtSBk4OlWCVmcUW2qo/edit#gid=0

Kiểm thử chức năng
